# Generated by Django 3.0.2 on 2020-02-01 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ViberUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=56)),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True)),
                ('viber_id', models.CharField(blank=True, max_length=36, null=True)),
                ('language', models.CharField(blank=True, max_length=8, null=True)),
                ('country', models.CharField(blank=True, max_length=8, null=True)),
                ('primary_device_os', models.CharField(blank=True, max_length=56, null=True)),
                ('device_type', models.CharField(blank=True, max_length=56, null=True)),
                ('api_version', models.CharField(blank=True, max_length=56, null=True)),
                ('viber_version', models.CharField(blank=True, max_length=56, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
